Update pbr minimum version to fix setuptools error
New patches to stable/victoria are failing with this error

    AttributeError: module 'setuptools.command.easy_install' has no
    attribute 'get_script_header'

whenever setuptools>=68.0.0 is installed, because pbr in this branch
uses a deprecated api that was removed.

Depends-On: https://review.opendev.org/c/openstack/requirements/+/894829
Change-Id: I7e8ab81602b7904568e4bfdfe45a60f25b6de61a