Bump SQLAlchemy requirement
This is primarily to fix the requirements-check job, which is failing
following the removal of excluded versions [1]:

    ERROR: Requirement for package SQLAlchemy excludes a version not excluded in the global list.
      Local settings : {'!=1.1.6', '!=1.1.7', '!=1.1.5', '!=1.1.8'}
      Global settings: set()
      Unexpected     : {'!=1.1.6', '!=1.1.7', '!=1.1.5', '!=1.1.8'}

[1] https://review.opendev.org/c/openstack/requirements/+/879743

Change-Id: I3f719c9b31a3ae61a3bc06b1646f915ddc4b341e